[package]
name = "rust-sls"
version = "0.1.0"
authors = ["ayankovsky <contact@arseny.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.64", features = ["derive"] }
serde_json = "1.0.64"
lambda_runtime = "0.3.0"
tokio = "1.5.0"
