service: rust-sls

frameworkVersion: '3'

provider:
  name: aws
  runtime: provided.al2
plugins:
  - serverless-rust-plugin

custom:
  rust:
    cargoLambda:
      docker: false

package:
  individually: true
functions:
  test:
    # handler value syntax is `{cargo-package-name}.{bin-name}`
    # or `{cargo-package-name}` for short when you are building a
    # default bin for a given package.
    handler: rust-sls.hello
    events:
      - http:
          path: /hello
          method: GET
