service: rust-sls

frameworkVersion: '3'

provider:
  name: aws
  runtime: provided.al2
plugins:
  - serverless-rust-plugin

custom:
  rust:
    cargoLambda:
      docker: false

package:
  individually: true
functions:
  hello:
    # handler value syntax is `{cargo-package-name}.{bin-name}`
    handler: rust-sls.hello
    events:
      - http:
          path: /hello
          method: GET

  hello2:
    handler: rust-sls.hello2
    events:
      - http:
          path: /hello2
          method: GET
